### ISSUE TITLE
Nginx error in 2024.2.1-beta

### ISSUE THREAD

**Issue by nexcode** [bitwarden/self-host#219] opened 2024-02-26 13:35 UTC
There is an error when updating from `2024.1.2-beta` to `2024.2.1-beta`:
```
WARN exited: nginx (exit status 1; not expected)
```

I checked inside the container:
```
nginx -t
2024/02/26 16:24:40 [emerg] 292#292: open() "/etc/nginx/http.d/bitwarden.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:37
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by nexcode** [comment] 2024-02-26 15:31
https://github.com/bitwarden/self-host/issues/210

**Comment by NovaSilentium** [comment] 2024-02-27 06:53
Duplicate of #3755

**Comment by NovaSilentium** [comment] 2024-02-27 06:55
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/server/issues/3755

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-02-27 09:54 UTC
