### ISSUE TITLE
Arch Linux Kernel >6.7 breaks MSSQL docker container

### ISSUE THREAD

**Issue by lateparty** [bitwarden/self-host#207] opened 2024-02-01 10:03 UTC
I have downgraded back to kernel version 6.6 per the suggestion in the community post linked below and temporarily resolved the issue but feel like there should be a formal bug tracker for this as the permanent solution is not to stay on kernel 6.6

My issue was near enough to exactly the same as the one contained in the link below. Copying the log excerpt below the link for better SEO of this issue tracker.

https://community.bitwarden.com/t/mssql-container-no-longer-accessible/62366

mssql container crash logs

```
This program has encountered a fatal error and cannot continue running at Thu Jan 18 03:14:28 2024
The following diagnostic information is available:

         Reason: 0x00000001
         Signal: SIGABRT - Aborted (6)
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 00005a6f7f625a9c <unknown>
                 00005a6f7f6254e2 <unknown>
                 00005a6f7f624af1 <unknown>
                 00007407b5408090 killpg+0x40
                 00007407b540800b gsignal+0xcb
                 00007407b53e7859 abort+0x12b
                 00005a6f7f59c692 <unknown>
                 00005a6f7f638c44 <unknown>
                 00005a6f7f66b248 <unknown>
                 00005a6f7f66b02a <unknown>
                 00005a6f7f5a850a <unknown>
                 00005a6f7f5a815f <unknown>
        Process: 47 - sqlservr
         Thread: 158 (application thread 0x1d8)
    Instance Id: e2ea39b0-4f2d-4644-ab00-ca4cee1f2ae8
       Crash Id: c7fffd40-5909-450c-b4c7-4ed8c9d51828
    Build stamp: e5dea205d0938e2848fb2509856a7e8f30783e6d5f62d0c88355e288de0db89a
Distribution: Ubuntu 20.04.4 LTS
Processors: 16
Total Memory: 16664141824 bytes
Timestamp: Thu Jan 18 03:14:28 2024
Last errno: 2
Last errno text: No such file or directory
```

Output of docker logs --tail 50 --follow --timestamps bitwarden-mssq:

```
2024-01-18T03:54:42.051341638Z /usr/bin/find: '/proc/42/task/191/ns': Permission denied
2024-01-18T03:54:42.051472909Z /usr/bin/find: '/proc/42/fd': Permission denied
2024-01-18T03:54:42.051481455Z /usr/bin/find: '/proc/42/map_files': Permission denied
2024-01-18T03:54:42.051486124Z /usr/bin/find: '/proc/42/fdinfo': Permission denied
2024-01-18T03:54:42.051489140Z /usr/bin/find: '/proc/42/ns': Permission denied
2024-01-18T03:54:42.051497786Z /usr/bin/find: '/proc/42/net': Invalid argument
2024-01-18T03:54:42.053321320Z /usr/bin/find: '/proc/42/task/42/fd': Permission denied
2024-01-18T03:54:42.053328794Z /usr/bin/find: '/proc/42/task/42/fdinfo': Permission denied
2024-01-18T03:54:42.053331830Z /usr/bin/find: '/proc/42/task/42/ns': Permission denied
2024-01-18T03:54:42.053334916Z /usr/bin/find: '/proc/42/task/42/net': Invalid argument
2024-01-18T03:54:42.053393328Z /usr/bin/find: '/proc/42/task/191/fd': Permission denied
2024-01-18T03:54:42.053399519Z /usr/bin/find: '/proc/42/task/191/fdinfo': Permission denied
2024-01-18T03:54:42.053402164Z /usr/bin/find: '/proc/42/task/191/ns': Permission denied
2024-01-18T03:54:42.053508197Z /usr/bin/find: '/proc/42/fd': Permission denied
2024-01-18T03:54:42.053511624Z /usr/bin/find: '/proc/42/map_files': Permission denied
2024-01-18T03:54:42.053521182Z /usr/bin/find: '/proc/42/fdinfo': Permission denied
2024-01-18T03:54:42.053523126Z /usr/bin/find: '/proc/42/ns': Permission denied
2024-01-18T03:54:42.053535068Z /usr/bin/find: '/proc/42/net': Invalid argument
2024-01-18T03:54:42.055235878Z /usr/bin/find: '/proc/42/task/42/fd': Permission denied
2024-01-18T03:54:42.055239985Z /usr/bin/find: '/proc/42/task/42/fdinfo': Permission denied
2024-01-18T03:54:42.055241719Z /usr/bin/find: '/proc/42/task/42/ns': Permission denied
2024-01-18T03:54:42.055248922Z /usr/bin/find: '/proc/42/task/42/net': Invalid argument
2024-01-18T03:54:42.055308897Z /usr/bin/find: '/proc/42/task/191/fd': Permission denied
2024-01-18T03:54:42.055313035Z /usr/bin/find: '/proc/42/task/191/fdinfo': Permission denied
2024-01-18T03:54:42.055316181Z /usr/bin/find: '/proc/42/task/191/ns': Permission denied
2024-01-18T03:54:42.055421302Z /usr/bin/find: '/proc/42/fd': Permission denied
2024-01-18T03:54:42.055424358Z /usr/bin/find: '/proc/42/map_files': Permission denied
2024-01-18T03:54:42.055428005Z /usr/bin/find: '/proc/42/fdinfo': Permission denied
2024-01-18T03:54:42.055436391Z /usr/bin/find: '/proc/42/ns': Permission denied
2024-01-18T03:54:42.055453864Z /usr/bin/find: '/proc/42/net': Invalid argument
2024-01-18T03:54:42.057092234Z /usr/bin/find: '/proc/42/task/42/fd': Permission denied
2024-01-18T03:54:42.057097694Z /usr/bin/find: '/proc/42/task/42/fdinfo': Permission denied
2024-01-18T03:54:42.057099598Z /usr/bin/find: '/proc/42/task/42/ns': Permission denied
2024-01-18T03:54:42.057109908Z /usr/bin/find: '/proc/42/task/42/net': Invalid argument
2024-01-18T03:54:42.057173219Z /usr/bin/find: '/proc/42/task/191/fd': Permission denied
2024-01-18T03:54:42.057175373Z /usr/bin/find: '/proc/42/task/191/fdinfo': Permission denied
2024-01-18T03:54:42.057177166Z /usr/bin/find: '/proc/42/task/191/ns': Permission denied
2024-01-18T03:54:42.057282848Z /usr/bin/find: '/proc/42/fd': Permission denied
2024-01-18T03:54:42.057285523Z /usr/bin/find: '/proc/42/map_files': Permission denied
2024-01-18T03:54:42.057290823Z /usr/bin/find: '/proc/42/fdinfo': Permission denied
2024-01-18T03:54:42.057293849Z /usr/bin/find: '/proc/42/ns': Permission denied
2024-01-18T03:54:42.057306213Z /usr/bin/find: '/proc/42/net': Invalid argument
2024-01-18T03:54:42.066837180Z dmesg: read kernel buffer failed: Operation not permitted
2024-01-18T03:54:42.067795501Z /usr/bin/timeout: failed to run command '/bin/journalctl': No such file or directory
2024-01-18T03:54:42.068682685Z /usr/bin/timeout: failed to run command '/bin/journalctl': No such file or directory
2024-01-18T03:54:42.069676634Z Thu Jan 18 03:54:42 UTC 2024 Capturing program information
2024-01-18T03:54:42.141268348Z Dump already generated: /var/opt/mssql/log/core.sqlservr.1_18_2024_3_52_0.42, moving to /var/opt/mssql/log/core.sqlservr.42.temp/core.sqlservr.42.gdmp
2024-01-18T03:54:42.142247379Z Moving logs to /var/opt/mssql/log/core.sqlservr.42.temp/log/paldumper-debug.log
2024-01-18T03:54:42.144412896Z Thu Jan 18 03:54:42 UTC 2024 Capturing program binaries
```

**Comment by NovaSilentium** [comment] 2024-02-01 14:53
Duplicate of #868

**Comment by NovaSilentium** [comment] 2024-02-01 14:54
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/microsoft/mssql-docker/issues/868

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-02-01 14:54 UTC
