### ISSUE TITLE
Impossible to update to 2024.11.0 self host

### ISSUE THREAD

**Issue by DimebagCFH** [bitwarden/self-host#308] opened 2024-11-17 15:15 UTC
Hello everyone,

I just noticed a new Bitwarden update.
I’ve always used these commands:
./bitwarden.sh updateself  
./bitwarden.sh update  
Any idea? When trying to update it,
here’s the message I get:
` |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

WARNING: This script is running as the root user!
If you are running a standard deployment this script should be running as a dedicated Bitwarden User as per the documentation.
Do you still want to continue? (y/n): y
Continuing....
bitwarden.sh version 2024.11.0
Docker version 20.10.23, build 876964a
docker: 'compose' is not a docker command.
See 'docker --help'
`

**Comment by pdk428** [comment] 2024-11-17 15:44
Same issue here

**Comment by pdk428** [comment] 2024-11-17 15:57
> Just install the `docker-compose-plugin` package. And remove the deprecated `docker-compose` from your systems. If you can't find the right package, add the official docker repositories to your sources.

I appreciate you. This did it.

**Comment by DimebagCFH** [comment] 2024-11-17 15:57
I don't understand why I have to update docker-compose?
I'm running all my applications on a synology, and I don't notice any issue with the other app when I have to update it

**Comment by DimebagCFH** [comment] 2024-11-18 12:18
It seems that the docker compose version on synology is not in V2.
Does anyone experience the same issue ?

**Comment by DimebagCFH** [comment] 2024-11-18 12:46
That's a pitty

**Comment by DimebagCFH** [comment] 2024-11-19 07:23
Someone seems found the solution by editing the run.sh and bitwarden.sh files
https://github.com/bitwarden/server/issues/5043

**Comment by Exportedthought** [comment] 2024-11-19 08:17
I wouldn't call modifying the scripts a solution, just a workaround. At any rate, given the suggestion to install the docker-compose-plugin above I realized that I had installed the docker engine via debian repositories, this seems to have been the root cause. After following the instructions provided direct from docker themselves (and rightfully linked in the bitwarden installation instructions) everything seems to be working as expected. All that said, it does seem likely that it would be a simple fix to just allow the docker-compose syntax and validate which applications are present within the script, since the containers did not have issues prior to this and even during all of my tinkering the containers were running happily in the background, but I certainly could be wrong on this.

**Comment by DimebagCFH** [comment] 2024-11-19 08:25
If i've just well understood your point,
You mean that it's worth to wait for a proper solution, in my case, waiting a fix from Synology and their Container Manager (docker solution provided by Synology)
I prefer to avoid any DIY on the system and experience some wrong side effect

**Comment by Exportedthought** [comment] 2024-11-19 08:35
> I've seem some workarounds in other issues and pull requests, but I don't know if and how long they work. Best would be, using a proper vm and install docker and bitwarden inside that vm

Personally this seems like the most reasonable option, if running a VM is possible on your hardware that seems to be the most clean of all the options. That way any future modifications/deprecations shouldn't cause any issues since you can bypass the obscurities of whatever synology is doing.

**Comment by DimebagCFH** [comment] 2024-11-19 08:51
Yes, exactly,
This is why, I'm a bit "pissed off" with Synology as we speak.
I choose that solution to avoid any waste of time to configure and setup all my applications needs.
To be honest, this issue is not really blocking, the application is still running, no critical notice regarding any potential security breach or whatever (cfr the release note)

So I can wait for the further actions provided by bitwarden and/or synology environment.

**Comment by SergeantConfused** [comment] 2024-11-19 11:58
Hello everyone,

Thank you all for your input. What is being discussed here is related to the [deprecation of Docker Compose V1](https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/); The Bitwarden server requires a more [recent version](https://bitwarden.com/help/install-on-premise-linux/#system-specifications) of Docker Engine and [Docker Compose](https://docs.docker.com/compose/releases/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2).

Some of the workarounds mentioned here may assist; However, please remember that the bitwarden.sh script would return to its default syntax after each ```updateself``` command, and use ```docker compose``` without a hyphen.

As a side note, the workaround shared by @Exportedthought in this [GitHub thread](https://github.com/bitwarden/server/issues/5043) could be related to [this](https://community.synology.com/enu/forum/1/post/185242).

Please feel free to try contacting the vendor of the device/operating system you're using and to see if they'd be able to update their environment.

I will now proceed and close this GitHub report; If you have any questions or concerns, you're more than welcome to [get in touch](https://bitwarden.com/help/) and please include a link to this GitHub report if you do.

Thank you all again,

**Closed by SergeantConfused** 2024-11-19 11:58 UTC

**Comment by bglf83** [comment] 2024-11-20 12:13
> Yes, exactly, This is why, I'm a bit "pissed off" with Synology as we speak. I choose that solution to avoid any waste of time to configure and setup all my applications needs. To be honest, this issue is not really blocking, the application is still running, no critical notice regarding any potential security breach or whatever (cfr the release note)
> 
> So I can wait for the further actions provided by bitwarden and/or synology environment.

I followed the directions from this link to add the docker compose v2 plugin on my synology: [](https://piotrkrzyzek.com/install-docker-compose-plugin-v2-on-synology-dsm-7/)

I used the current version of docker compose v2 (v2.30.3). I assume we will have to re-run this periodically to install the most current release of docker compose. I can confirm my bitwarden updates did work as expected after the update. 

```
DOCKER_CONFIG=${DOCKER_CONFIG:-/usr/local/lib/docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.30.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
```

**Comment by DimebagCFH** [comment] 2024-11-20 14:46
@bglf83 
Thanks a lot for your help,
Just to be sure, there is no side effect with that plugin I hope
Because I have several docker running on my synology, some of them are managed directly through Portainer (via container manager)

**Comment by bglf83** [comment] 2024-11-21 02:11
> @bglf83 Thanks a lot for your help, Just to be sure, there is no side effect with that plugin I hope Because I have several docker running on my synology, some of them are managed directly through Portainer (via container manager)

No downfall that I can tell. I also have Portainer. I am not sure if it should be installed as single user or multi-user though. I did multi-user.

**Comment by DimebagCFH** [comment] 2024-11-21 12:20
Thanks again @bglf83 
I've tried it, and everything is working well, including my other docker applications, no side effect as we speak
