### ISSUE TITLE
bitwarden.sh update 2024.5.0

### ISSUE THREAD

**Issue by Schnuecks** [bitwarden/self-host#260] opened 2024-05-17 03:53 UTC
bitwarden.sh updateself
bitwarden.sh update

Unhandled exception. YamlDotNet.Core.YamlException: (Line: 6, Col: 1, Idx: 193) - (Line: 6, Col: 1, Idx: 193): Exception during deserialization
 ---> System.Runtime.Serialization.SerializationException: Property 'compose_version' not found on type 'Bit.Setup.Configuration'.
   at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty(Type type, Object container, String name, Boolean ignoreUnmatched)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   --- End of inner exception stack trace ---
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at Bit.Setup.Context.LoadConfiguration() in /home/runner/work/server/server/util/Setup/Context.cs:line 154
   at Bit.Setup.Program.PrintEnvironment() in /home/runner/work/server/server/util/Setup/Program.cs:line 169
   at Bit.Setup.Program.Main(String[] args) in /home/runner/work/server/server/util/Setup/Program.cs:line 61

_Ursprünglich gepostet von @Schnuecks in https://github.com/bitwarden/self-host/issues/259_

**Comment by sammbw** [comment] 2024-05-17 05:01
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

In the meantime, this looks very similar to this previous issue from the 2024.4.2 release here: https://github.com/bitwarden/server/issues/4059

You may find some steps in the comments that help remedy your environment.

Thanks!

**Comment by Schnuecks** [comment] 2024-05-17 05:10
Thats my issue yes. I comment out compose_version in config.yaml and the update is done.

**Comment by WardenTechnologyServices** [comment] 2024-05-17 19:48
Hello, 

I have the same issue when updating from 2024.4.0 and I found following the replies solved the issue from 
* [Nini81](https://github.com/bitwarden/server/issues/4059#issuecomment-2102065153)
* [ninji](https://github.com/bitwarden/server/issues/4059#issuecomment-2115942678) on the [bitwarden/server#4059](https://github.com/bitwarden/server/issues/4059).

**Steps**
* I made sure that Docker-CE and Docker Compose (Standalone) were updated to the latest versions
* Commented out `compose_version:` in `bwdata/config.yml'
* './bitwarden.sh updateself'
* './bitwarden.sh update'
* Updated correctly to 2024.5.0

I then noticed that 'compose_version:' was removed from 'bwdata/config.yml' as well.
I was using Virtualised Debian 12 and Kernel 6.1.0-12-amd64

Thanks.

**Comment by djsmith85** [comment] 2024-05-18 17:06
Duplicate of https://github.com/bitwarden/server/issues/4059

**Closed** 2024-05-18 17:07 UTC
