### ISSUE TITLE
2024.4.2  Error when updating.

### ISSUE THREAD

**Issue by ilkevinli** [bitwarden/self-host#254] opened 2024-05-07 00:42 UTC
I am receiving the below error when updating to the newest version 2024.4.2. The previous version 2024.4.1 was running fine on a ubuntu VM. Any suggestions ? Thanks.

![Bitwarden](https://github.com/bitwarden/self-host/assets/10118629/b5354f6b-c659-4be2-a434-ca14d3f8c5e2)

**Comment by BBGhub** [comment] 2024-05-07 01:19
Hi there!

Thank you for your report, it seems like it is a duplicate of this one 
(https://github.com/bitwarden/server/issues/4059)]. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by BBGhub** 2024-05-07 01:19 UTC

**Comment by Proximus888** [comment] 2024-05-07 12:21
> I am receiving the below error when updating to the newest version 2024.4.2. The previous version 2024.4.1 was running fine on a ubuntu VM. Any suggestions ? Thanks.
> 
> ![Bitwarden](https://private-user-images.githubusercontent.com/10118629/328352024-b5354f6b-c659-4be2-a434-ca14d3f8c5e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODQ2MzcsIm5iZiI6MTcxNTA4NDMzNywicGF0aCI6Ii8xMDExODYyOS8zMjgzNTIwMjQtYjUzNTRmNmItYzY1OS00YmUyLWE0MzQtY2ExNGQzZjhjNWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEyMTg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNjBlYjdmOGQyMWI0ZWU1MjMwYTNlNzJmOGQ4MWRkMzZkNzRiOWE1YWE3NDQyYWM4NGJjOGI4Y2FkOWFiMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v-Wc5CwQJofEIFy6NAqjkDkgImoVKvd5o5tuHjZkJo0)

I have the same issue. Did you find a way to resolve it?

https://github.com/bitwarden/server/issues/4059 issue doesn't exist.
